In [1]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# import data
n_samples = 300
cancer = datasets.load_breast_cancer()
X,y = cancer['data'], cancer['target']
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=42)

In [4]:
X.shape[0]

569

In [17]:
# Example: use LogisticRegression and evaluate the model
logreg = linear_model.LogisticRegression(C=1e3)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print('precision: ', accuracy_score(y_test, y_pred))

precision:  0.9415204678362573


/home/lation/anaconda3/envs/prml/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
X.shape[1]

30

In [7]:
y[0]

0

In [13]:
sum = [np.zeros(X.shape[1]), np.zeros(X.shape[1])]
for i in range (X.shape[0]):
    sum[y[i]] += X[i] / X.shape[1]

In [14]:
sum

[array([ 6.69453792,  3.80734956,  6.81014732,  6.50155316,  3.28808155,
         5.47035802,  6.38578684,  7.12173664,  3.03075163, -0.11772392,
         5.20075423, -0.07614357,  5.09994468,  5.0274561 , -0.61455302,
         2.6868739 ,  2.32676329,  3.74184683, -0.05980608,  0.71502592,
         7.12026884,  4.18990932,  7.17951189,  6.72935296,  3.86493466,
         5.4195967 ,  6.04878507,  7.2771922 ,  3.81751946,  2.96998626]),
 array([-6.69453792, -3.80734956, -6.81014732, -6.50155316, -3.28808155,
        -5.47035802, -6.38578684, -7.12173664, -3.03075163,  0.11772392,
        -5.20075423,  0.07614357, -5.09994468, -5.0274561 ,  0.61455302,
        -2.6868739 , -2.32676329, -3.74184683,  0.05980608, -0.71502592,
        -7.12026884, -4.18990932, -7.17951189, -6.72935296, -3.86493466,
        -5.4195967 , -6.04878507, -7.2771922 , -3.81751946, -2.96998626])]

In [10]:
sum1 = [np.zeros(X.shape[1]), np.zeros(X.shape[1])]
for i in range (X.shape[0]):
    for j in range (X.shape[1]):
        sum1[y[i]][j] += X[i][j]

In [11]:
sum1

[array([200.83613751, 114.22048683, 204.30441968, 195.04659486,
         98.6424466 , 164.11074063, 191.57360531, 213.65209925,
         90.92254899,  -3.5317176 , 156.02262686,  -2.28430712,
        152.99834054, 150.82368287, -18.4365905 ,  80.60621687,
         69.80289862, 112.25540478,  -1.79418233,  21.45077747,
        213.60806519, 125.69727954, 215.38535668, 201.88058867,
        115.94803966, 162.58790104, 181.46355224, 218.31576611,
        114.52558386,  89.09958778]),
 array([-200.83613751, -114.22048683, -204.30441968, -195.04659486,
         -98.6424466 , -164.11074063, -191.57360531, -213.65209925,
         -90.92254899,    3.5317176 , -156.02262686,    2.28430712,
        -152.99834054, -150.82368287,   18.4365905 ,  -80.60621687,
         -69.80289862, -112.25540478,    1.79418233,  -21.45077747,
        -213.60806519, -125.69727954, -215.38535668, -201.88058867,
        -115.94803966, -162.58790104, -181.46355224, -218.31576611,
        -114.52558386,  -89.09958778])

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [32]:
x = np.array([np.array([]),np.array([])])
for i in range (X.shape[0]):
    # print(X[i])
    np.insert(x[y[i]],0,X[i],0)

# 计算均值
mu = np.array([np.zeros(X.shape[1]), np.zeros(X.shape[1])])
for i in range (2):
    for j in range (x[i].shape[0]):
        mu[i] += x[i][j] / x[i].shape[0]

In [33]:
x[0]

array([], dtype=float64)

In [30]:
aa = np.array([[3,4],[5,6]])
bb = np.array([1,2])
np.insert(aa,0,bb)

array([1, 2, 3, 4, 5, 6])

In [53]:
x = [[],[]]
x[0].append(X[0])

In [54]:
x

[[array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
          3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
          2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
          1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
          1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
          2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])],
 []]

In [57]:
x = [[],[]]
for i in range (X.shape[0]):
    x[y[i]].append(X[i])

In [72]:
mu = [[],[]]
for i in range (2):
    for j in range (len(x[i])):
        mu[i] += x[i][j] / len(x[i])


ValueError: operands could not be broadcast together with shapes (0,) (30,) 

In [71]:
shape(x[0])

NameError: name 'shape' is not defined